from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys
import tempfile
from collections.abc import Sequence

INCLUDE_PATH = pathlib.Path(__file__).parent / "wlroots" / "include"

if not INCLUDE_PATH.exists():
    INCLUDE_PATH.mkdir()

WAYLAND_PROTOCOLS = [
    "stable/xdg-shell/xdg-shell.xml",
    "unstable/idle-inhibit/idle-inhibit-unstable-v1.xml",
    "unstable/pointer-constraints/pointer-constraints-unstable-v1.xml",
]
WLROOTS_PROTOCOLS = [
    "protocol/wlr-output-power-management-unstable-v1.xml",
    "protocol/wlr-layer-shell-unstable-v1.xml",
]


def get_wlroots_protocols_dir() -> pathlib.Path:
    return pathlib.Path(__file__).parent / "wlroots"


def get_wayland_protocols_dir() -> pathlib.Path | None:
    args = ["pkgconf", "--variable=pkgdatadir", "wayland-protocols"]
    try:
        output = subprocess.check_output(args).decode().strip()
    except subprocess.CalledProcessError:
        return None

    if output:
        return pathlib.Path(output)
    return None


def header_filename(xml_file: pathlib.Path) -> str:
    return f"{xml_file.stem}-protocol.h"


def header_output_path(
    input_xml: pathlib.Path, output_dir: pathlib.Path
) -> pathlib.Path:
    return output_dir / header_filename(input_xml)


def generate_protocol_header(
    input_xml: pathlib.Path, output_dir: pathlib.Path
) -> pathlib.Path:
    output_path = header_output_path(input_xml, output_dir)
    subprocess.check_output(
        ["wayland-scanner", "server-header", str(input_xml), str(output_path)]
    )
    return output_path


def check(protocols: list[pathlib.Path]) -> None:
    expected_protocol_files = {
        header_filename(protocol_xml) for protocol_xml in protocols
    }
    protocol_files = {
        path.name for path in INCLUDE_PATH.iterdir() if path.suffix == ".h"
    }

    if expected_protocol_files != protocol_files:
        missing_files = list(expected_protocol_files - protocol_files)
        unexpected_files = list(protocol_files - expected_protocol_files)
        raise ValueError(
            "Error in wlroots/include directory."
            f"\nMissing files: {missing_files}"
            f"\nUnexpected files: {unexpected_files}"
        )

    errors = []
    for protocol_xml in protocols:
        protocol_header_file = INCLUDE_PATH / header_filename(protocol_xml)
        with protocol_header_file.open() as f:
            protocol_header = f.readlines()

        with tempfile.TemporaryDirectory() as output_dir:
            generated_file = generate_protocol_header(
                protocol_xml, pathlib.Path(output_dir)
            )
            with generated_file.open() as f:
                generated_header = f.readlines()

        if len(protocol_header) != len(generated_header):
            errors.append(
                f"Mismatch line count in wlroots/include/{generated_file.name}"
            )
            continue

        for i, (generated_line, line) in enumerate(
            zip(generated_header, protocol_header)
        ):
            if "Generated by wayland-scanner" in line:
                continue

            if generated_line != line:
                errors.append(f"Mismatch {protocol_xml.name} in line {i + 1}")
                errors.append(f"- New: {generated_line.strip()}")
                errors.append(f"- Old: {line.strip()}")
                continue

    if errors:
        raise ValueError("Protocol header check failed:\n" + "\n".join(errors))


def generate(protocols: list[pathlib.Path]) -> None:
    for protocol_xml in protocols:
        generate_protocol_header(protocol_xml, INCLUDE_PATH)


def parse_args(
    argv: Sequence[str] | None,
) -> tuple[pathlib.Path | None, pathlib.Path | None, bool, bool]:
    parser = argparse.ArgumentParser()
    parser.add_argument("--wayland-dir", type=pathlib.Path)
    parser.add_argument("--wlroots-dir", type=pathlib.Path)
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    return args.wayland_dir, args.wlroots_dir, args.generate, args.check


def resolve_protocols(
    wayland_dir: pathlib.Path | None = None, wlroots_dir: pathlib.Path | None = None
) -> list[pathlib.Path]:
    if wayland_dir is None:
        wayland_dir = get_wayland_protocols_dir()
    if wlroots_dir is None:
        wlroots_dir = get_wlroots_protocols_dir()

    if wayland_dir is None or not wayland_dir.exists():
        raise ValueError(f"Wayland protocols directory does not exist: {wayland_dir}")
    if not wlroots_dir.exists():
        raise ValueError(f"Wlroots directory does not exist: {wlroots_dir}")

    protocols = [wayland_dir / xml_file for xml_file in WAYLAND_PROTOCOLS] + [
        wlroots_dir / xml_file for xml_file in WLROOTS_PROTOCOLS
    ]

    for protocol in protocols:
        if not protocol.exists():
            raise ValueError(f"Protocol does not exist: {protocol}")

    return protocols


if __name__ == "__main__":
    wayland_dir, wlroots_dir, do_generate, do_check = parse_args(sys.argv[1:])
    protocols = resolve_protocols(wayland_dir, wlroots_dir)

    if do_generate:
        generate(protocols)
    elif do_check:
        check(protocols)
    else:
        # Print the list of protocols that would be generated or checked
        print("Protocols to be generated or checked:")
        for protocol in protocols:
            print(f"- {header_output_path(protocol, INCLUDE_PATH)}")
        print("Use --generate to generate headers")
        print("Use --check to check existing headers.")
